name: Publish Image

on:
  push: # push 到主分支自动 发布
    branches: ["main"]
    paths-ignore: # 忽略一些不必要的文件
      - ".gitignore"
      - "README.md"
      - ".vscode/**"
      - ".idea/**"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Go Build Action
        uses: calxus/go-build-action@latest
        with:
          # The namespace the image is to be tagged as
          IMAGE_NAMESPACE: 'gtadam'
          # The name the image is to be tagged as
          IMAGE_NAME: 'go-build'
          # The version the image is to be tagged as
          IMAGE_VERSION: 'latest'
          # The username used to authenticate to dockerhub
          DOCKER_USERNAME: 'docker'
          # The password used to athenticate to dockerhub
          DOCKER_PASSWORD: 'password'
